name: hex CI

on:
  push:
    branches: ['main']

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Decrypt large secret
        run: ./decrypt_secret.sh
        env:
          HCA_SECRET: ${{ secrets.HCA_SECRET }}
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: echo $HOME/secrets/token_snyk.txt
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: npm
      - name: set up and build npm
        run: make setup
      - name: run tests
        run: make test
      - name: Run linter
        run: make lint
