name: hex CI

on:
  push:
    branches: ['main']

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: set up and build npm
        run: make setup
        with:
          cache: npm
#      - name: start npm
#        run: make start
      - name: run tests
        run: make test
      - name: Run linter
        run: make lint
